### ISSUE TITLE
Possíveis datasets

### ISSUE THREAD

**Issue by AlissonRP** [AlissonRP/Pokemom#1]
* # Vou colocar o link de algumas bases interessantes
  * [Criar um sistema de recomendação de animes](https://www.kaggle.com/CooperUnion/anime-recommendations-database): Pra ser sincero não sei como vai funcionar para os modelos que ele ensinou, mas a gnte não precisa ficar preso aos que ele ensinou como modelo final.
  * [Prever o tipo do pokemon](https://www.kaggle.com/abcsds/pokemon): Esse parece muito legal 
  *

**Comment by VitorBSP** [comment]
Voto em pokemon!

**Comment by AlissonRP** [comment]
Blz dataset escolhido por unanimidade
