### ISSUE TITLE
O que deve ser feito 

### ISSUE THREAD

**Issue by AlissonRP** [AlissonRP/Pokemom#6]
- [x] Titulo e resumo 
- [x] Introdução
- [x] Análise Descritiva (Vítor)
- [x] Desenvolvimento 
- [x] Referências  
- [x] Descrever brevemente o MLG (estrutura, possíveis covariáveis, função de ligação, distribuição assumida ou possíveis distribuições a serem assumidas), 
- [ ] Características e método de estimação (outras informações sobre o modelo que acharem necessárias)
- [ ] Explicitar as características da variável dependente(continua, discreta, positiva, num intervalo fechado, contagem, etc),
- [ ] Justificar a(s) distribuição(oes) assumida(s) para ela. 
- [x] Faca os gráficos importantes utilizando os resíduos adequados (Vítor)
- [x] Após o modelo ser selecionado, o modelo deve ser apresentado e validado. (Vítor)
- [x] Apresente as analises, os testes e os gráficos feitos para este modelo selecionado (Vítor)
- [x] Interprete o modelo selecionado. (Quais variáveis mais influenciam em sua variável dependente? Positivamente ou negativamente? Faz sentido com o problema pratico?) (Vítor)
- [ ] Númerar Gráficos e Tabelas.

**Comment by VitorBSP** [comment]
- [ ] Caracterização do que são pokémons lendários;
- [ ] Comentários para as matrizes de confusão do modelos;
- [ ] Terminar os modelos tunnados;
- [ ] Ajeitar melhor a parte o arquivo de medidas de influência (Se houver tempo, eu faço)
- [ ] Infelizmente, remover o link do PokeTrainer
- [ ] Apresentação
